# Imputing Missing Values in python

- Missing values are those values which are not present in dataset like NaN, NA, None
- It can be handle by:
    - `removing`
    - `imputing`
    - `using`

In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 


data = sns.load_dataset("titanic")
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [22]:
# check number of missing values in each column
data.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [23]:
# drop deck column
data = data.drop('deck', axis=1)
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [24]:
data.isnull().sum().sort_values(ascending=False)

age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [25]:
data['age'] = data['age'].fillna(data['age'].mean())
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [26]:
data.isnull().sum().sort_values(ascending=False)

embarked       2
embark_town    2
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
class          0
who            0
adult_male     0
alive          0
alone          0
dtype: int64

# Median Imputation

In [27]:
df = sns.load_dataset("titanic")

df['age'] = df['age'].fillna(df['age'].median())

#show first 10 rows
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,28.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

# Mode Categorical Imputation

In [28]:
df = sns.load_dataset("titanic")
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['deck'] = df['deck'].fillna(df['deck'].mode()[0])
df['age'] = df['age'].fillna(round(df['age'].mean(), 0))

In [29]:
df.isnull().sum(). sort_values(ascending=False)
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,C,Southampton,no,True
5,0,3,male,30.0,0,0,8.4583,Q,Third,man,True,C,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,C,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,C,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,C,Cherbourg,yes,False

# K Nearest Neighbour Method

In [30]:
df = sns.load_dataset('titanic')
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [31]:
from sklearn.impute import KNNImputer

# call the KNN with 4 neighbors
imputer = KNNImputer(n_neighbors=4)

# impute the missing values in the 'age' column

#  fit transform means it will first learn from the data and then transform it
# first fit the model on the data then transform the data
# df['age'] = inputer.fit(df[['age']].transform(df[['age']]) can be also done like this
df['age'] = imputer.fit_transform(df[['age']])

df.isnull().sum().sort_values(ascending=False)

deck           688
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

# Advance Techinique
## Multiple Imputation by Chained Equations (MICE)

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#load dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [33]:
 df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [34]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [35]:
# encode the data using label encoding
# from sklearn.preprocessing import LabelEncoder 

# columns_to_encode = ["sex", "embarked", 'who', 'deck', 'class', 'embark_town', 'alive', 'adult_male']

# encoder = LabelEncoder()

# df['sex'] = encoder.fit_transform(df['sex'])
# df['embarked'] = encoder.fit_transform(df['embarked'])
# df['who'] = encoder.fit_transform(df['who'])
# df['deck'] = encoder.fit_transform(df['deck'])
# df['class'] = encoder.fit_transform(df['class'])
# df['embark_town'] = encoder.fit_transform(df['embark_town'])
# df['alive'] = encoder.fit_transform(df['alive'])
# df['adult_male'] = encoder.fit_transform(df['adult_male'])



# this and the method below are both the same one use loop another use no loop

In [36]:
from sklearn.preprocessing import LabelEncoder

# Column to encode
columns_to_encode = ["sex", "embarked", 'who', 'deck', 'class', 'embark_town', 'alive', 'adult_male']

label_encoders = {}

for col in columns_to_encode:
     le = LabelEncoder()

     df[col] = le.fit_transform(df[col])
     label_encoders[col] = le

df.head()
label_encoders

{'sex': LabelEncoder(),
 'embarked': LabelEncoder(),
 'who': LabelEncoder(),
 'deck': LabelEncoder(),
 'class': LabelEncoder(),
 'embark_town': LabelEncoder(),
 'alive': LabelEncoder(),
 'adult_male': LabelEncoder()}

### this below part is KNN imputer which is also regression imputer

In [37]:
# impute the missing values with ItrativeImputer
# it will first run and the iteration mean it will run that much time and will improve what it done wrong

# it will iterate 10 time on one column to correct whole data if it miss in a iteration and then it will find average of that missing value
# from sklearn.impute import IterativeImputer
imputer = IterativeImputer(max_iter=10)
columns_to_inpute = ['age', 'embark_town', 'embarked', 'deck']

for col in columns_to_inpute:
    # the 2D array mean all the columns are contributing to predict the value of the column which is missing
    # it predict value on the basics of all the columns 
    df[col] = imputer.fit_transform(df[[col]])

df.isnull().sum().sort_values(ascending=False)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2.0,2,1,1,7.0,2.0,0,False
1,1,1,0,38.0,1,0,71.2833,0.0,0,2,0,2.0,0.0,1,False
2,1,3,0,26.0,0,0,7.9250,2.0,2,2,0,7.0,2.0,1,True
3,1,1,0,35.0,1,0,53.1000,2.0,0,2,0,2.0,2.0,1,False
4,0,3,1,35.0,0,0,8.0500,2.0,2,1,1,7.0,2.0,0,True

In [38]:
# reverse transform the encoded columns to original values
#IM fro reverse encoding i must have to run only labelencoder or imputer on data bcz the other algorithm will make it hard to reverse categorical data bcz it will change the data to float or int

for col in columns_to_encode:
    le = label_encoders[col]
    df[col] = le.inverse_transform(df[col].astype(int))

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# Regression Imputation

In [39]:
# load dataset
df = sns.load_dataset('titanic')

# count null or missing values in each column  
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [40]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [41]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error
from sklearn.impute import SimpleImputer 

df = sns.load_dataset('titanic')

df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [42]:
# drop deck column
df.drop('deck',axis=1, inplace=True)

df.isnull().sum().sort_values(ascending=False)

age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

In [43]:
# label encode data again for RandomForest
from sklearn.preprocessing import LabelEncoder

columns_to_encode = ['sex', 'embarked', 'who', 'class', 'embark_town', 'alive']

# dictionary to stroe label encode of each column
label_encoders = {}

for col in columns_to_encode:
    le = LabelEncoder()
# encode all the above columns
    df[col] = le.fit_transform(df[col])

# store label encoder in dictionary
    label_encoders[col] = le

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [44]:
# split the dataset into two parts one with missing values and one with no missing values
# getting all the rows where age is missing
df_with_missing = df[df['age'].isna()]

# remove all the rows which have age missing bcz we have put all them into df_with_missing
df_without_missing = df.dropna()

# df_with_missing.head()
# df_without_missing.head()

In [45]:
print('The shape of the original dataset is: ', df.shape)
print('The shape of the dataset with missing value is: ', df_with_missing.shape)
print('The shape of the dataset without missing value is: ', df_without_missing.shape)

The shape of the original dataset is:  (891, 14)
The shape of the dataset with missing value is:  (177, 14)
The shape of the dataset without missing value is:  (714, 14)

In [46]:
df_with_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,1,NaN,0,0,8.4583,1,2,1,True,1,0,True
17,1,2,1,NaN,0,0,13.0000,2,1,1,True,2,1,True
19,1,3,0,NaN,0,0,7.2250,0,2,2,False,0,1,True
26,0,3,1,NaN,0,0,7.2250,0,2,1,True,0,0,True
28,1,3,0,NaN,0,0,7.8792,1,2,2,False,1,1,True

In [47]:
df_without_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [48]:
print(df.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [49]:
# Regression Imputation  
# Now here we will take all the colums as x i.e features/inputs to predict the missing age colums
from sklearn.metrics import r2_score, mean_absolute_error, mean_absolute_percentage_error, mean_squared_error
# First we will drop age from the without missing values bcz there age is avaliable
# these both values are known to us X and y
# take X as all the rows from dataframe without age 
X = df_without_missing.drop(['age'], axis=1)
# take y as the age column bcz we know that
y = df_without_missing['age']

# Split the data into test train 80% train 20% test
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

# n_estimator mean how many trees we want to run in random forest regrerssor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model = rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)
print("RMSE for Random Forest Imputation: ", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score for Random Forest Imputation: ",r2_score(y_test, y_pred))
print("MAE for Random Forest Imputation: ", mean_absolute_error(y_test, y_pred))
print("MAPE for Random Forest Imputation: ", mean_absolute_percentage_error(y_test, y_pred))

RMSE for Random Forest Imputation:  11.081260589808045
R2 Score for Random Forest Imputation:  0.33769388288226154
MAE for Random Forest Imputation:  8.666661815622195
MAPE for Random Forest Imputation:  0.40839466096086574

In [50]:
df_with_missing.isnull().sum().sort_values(ascending=False)

age            177
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [51]:
# predict the missing values

# here the paramater act as X
# it mean just drop the age which is y from the missing values and predict the age bcz the df_with_missing all other columns are features 
y_pred = rf_model.predict(df_with_missing.drop(['age'], axis=1))
# y_pred

In [52]:
# remove warning
import warnings
warnings.filterwarnings('ignore')

# replace the missing values with the predicted values
df_with_missing['age'] = y_pred

df_with_missing.isnull().sum().sort_values(ascending=False)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [53]:
# concate the dataFrames
# now in df_with_missing we have age predicted the age is not missing
df_complete = pd.concat([df_with_missing, df_without_missing], axis=0)
print('The Shape of the complete dataframe is ', df_complete.shape)

df_with_missing.head()

The Shape of the complete dataframe is  (891, 14)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,1,32.976583,0,0,8.4583,1,2,1,True,1,0,True
17,1,2,1,35.642218,0,0,13.0000,2,1,1,True,2,1,True
19,1,3,0,18.347000,0,0,7.2250,0,2,2,False,0,1,True
26,0,3,1,35.571486,0,0,7.2250,0,2,1,True,0,0,True
28,1,3,0,20.651429,0,0,7.8792,1,2,2,False,1,1,True

In [60]:
# now inverse transform the whole data again to make categorical variable again categorical
for col in columns_to_encode:
    le = label_encoders[col]

    df_complete[col] = le.inverse_transform(df[col])


# df_complete['age'] = round(df_complete['age'])

df_complete.head()

df_complete.to_csv('titanic.csv', index=False)